# Generated by .github/workflows/release.yml from
# .github/homebrew/slidepack.rb.tmpl. Do not edit in the tap by hand — the
# next release will overwrite it. Edit the template in pridkett/slidepack.
class Slidepack < Formula
  desc "Pack a presentation directory into a single self-contained HTML file"
  homepage "https://pridkett.github.io/slidepack"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pridkett/slidepack/releases/download/v0.1.0/slidepack_0.1.0_darwin_arm64.tar.gz"
      sha256 "e3cd6da0b43608f681abbc93ca4f1ec9f7bfa5353442698ba0031b329153c8d8"
    end

    on_intel do
      url "https://github.com/pridkett/slidepack/releases/download/v0.1.0/slidepack_0.1.0_darwin_amd64.tar.gz"
      sha256 "2348166e2d209387a7a54481d7e36048f54d0a03b48fc0153e748015ca067ffa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pridkett/slidepack/releases/download/v0.1.0/slidepack_0.1.0_linux_arm64.tar.gz"
      sha256 "1fddadf784850540e0c58b1e91bcce3352c929b8b950ea57423e80e347c12c77"
    end

    on_intel do
      url "https://github.com/pridkett/slidepack/releases/download/v0.1.0/slidepack_0.1.0_linux_amd64.tar.gz"
      sha256 "b050ed010c9d66cf254238a2efca490bb9e68a7d7ee3d076643e7bfa861fafb8"
    end
  end

  def install
    bin.install "slidepack"
    doc.install "README.md"
    doc.install "docs" => "docs"
  end

  test do
    assert_match "\"name\":\"slidepack\"", shell_output("#{bin}/slidepack version --json")

    # A presentation is any directory with an entry document, so the smallest
    # honest end-to-end check is pack -> unpack -> compare bytes.
    (testpath/"deck").mkpath
    (testpath/"deck/index.html").write("<!doctype html><title>t</title><h1>hello</h1>\n")

    system bin/"slidepack", "pack", testpath/"deck", "-o", testpath/"deck.html"
    assert_path_exists testpath/"deck.html"

    system bin/"slidepack", "unpack", testpath/"deck.html", "--output", testpath/"out"
    assert_equal (testpath/"deck/index.html").read, (testpath/"out/index.html").read
  end
end
